name: SAST
on: [push]

jobs:
  sast:
    runs-out: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Initialize CodeQL
        uses: github/codeql-action/init@3
        with:
          languages: 'javascript'
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@3
      - name: Save CodeQL SARIF report
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/juice-shop/results/javascript.sarif
